### ISSUE TITLE
entity

### ISSUE THREAD

**Issue by jkuchar** [jkuchar/PA165-java-project#3]
vyrobit entity podle diagramu z dokumentace
- [x] @jkuchar user #6 
- [x] @jakubsarmir car #9
- [x] @rtrembecky log item abstract class #7
- [x] @charlliz log items

**Comment by jakubsarmir** [comment]
beriem car ?

**Comment by jkuchar** [comment]
@jakubsarmir klidne, ale vem v poraz diskusi z #4

**Comment by jkuchar** [comment]
@jakubsarmir nevidím nikde Pull Request na Car, kdy ho plánuješ poslat?
