### ISSUE TITLE
jak na vyrazeni auta?

### ISSUE THREAD

**Issue by jkuchar** [jkuchar/PA165-java-project#4]

**Comment by charlliz** [comment]
Ja som stále za to aby to mohol daný Manager auto editovať - veď je celkom nepohodlné ak spraví náhodou preklep, že nemôže žiadne informácie upraviť, ale musí kontaktovať Admina. A je úplne jedno že je to deštrukčná činnosť, fakt nejde o žiadny bankový systém. Mazať nech nemôže ale editovať entity kvôli praktičnosti by som mu dovolila.

**Comment by jkuchar** [comment]
Editace: proč ne.

Šlo mi o to, že jsme v entitách na papír nezachytili use-case o vyřazení auta z evidence, na což bychom neměli zapomenout.

**Comment by charlliz** [comment]
To je pravda, ono by potom bolo vhodné niekde uchovávať stav auta. Možno nejaký enum ako DISCARDED, BEING REPAIRED (je nedostupné ale nie z dôvodu pôžičky), AVAILABLE (neviem nájsť vhodný ekvivalent pre auto, ktoré sa požičiava)

**Comment by jkuchar** [comment]
Přijde mi to dobré 👍

**Comment by jakubsarmir** [comment]
![uc_diagram2](https://cloud.githubusercontent.com/assets/22774880/19758039/a4dc926e-9c26-11e6-94bd-3fbe7c7255a2.png)

podla mna vyradenie z evidencie tam je

**Comment by charlliz** [comment]
U use-case to je, v class diagrame to chýba ;)
