### ISSUE TITLE
Změna názvu Facade a Services

### ISSUE THREAD

**Issue by jkuchar** [jkuchar/PA165-java-project#40]
Pročetl jsem si zadání a navrhuji přejmenovat:
- `Facade` -> `Adapter` (viz diskuse s zaskakujícím cvičícím)

Hlasujme tedy:
var 1) přejmenovat `Facade` -> `Adapter`
var 2) nic nepřejmenovávat

Já jsem pro 1)

**Comment by jakubsarmir** [comment]
nieco som zapocul, neviem sice konkretny dovod, ale je to detail ktory je asi spravnejsi, som za premenovanie

**Comment by jkuchar** [comment]
Důvod je poměrně jednoduchý: Facade je něco, co zjednodušuje přístup do něčeho co má pod sebou a tím poskytuje zjednodušený interface. Zároveň interface definuje. Z toho plyne, že facade by měla být součástí té části, kterou obaluje.

Adapter kdežto má za úkol převézt data z jednoho formátu do druhého. V našem případě pro REST a pro MVC GUI. Adaptérů bývá typicky více pro adaptaci do více "podob".

**Comment by rtrembecky** [comment]
ja sa zdrzim hlasovania

**Comment by charlliz** [comment]
Hmm to vážne teraz riešime takéto nepodstatné veci?

**Comment by rtrembecky** [comment]
no ja nemam problem sa vyjadrit aj k niecomu menej podstatnemu ako tomuto :D nemusis to riesit teraz, ale eventualne tu raz mozes napisat tvoj nazor

**Comment by jkuchar** [comment]
Vzhledem k diskusi na messangeru, že balík api je jen definice API a service obsahuje facade, které je implementují, budou fasády jen jedny a až vrstva nad ní si bude muset data upravit. Tam bude tedy adapter.

**Comment by jakubsarmir** [comment]
vdaka za vysvetlenie :)
